<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoreid" nsURI="http://www.emftext.org/ecoreid/1.0" nsPrefix="ecoreid">
  <eClassifiers xsi:type="ecore:EClass" name="EcoreID">
    <eOperations name="getEModelElement" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.emftext.language.ecoreid.util.EcoreIDResolverUtil.resolveEcoreID(this, ePackage);"/>
      </eAnnotations>
      <eParameters name="ePackage" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    </eOperations>
    <eOperations name="isQualified" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (names.size() > 1);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="names" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterTypeNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitlyNoParametersSpecified"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreIDList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreIDs" lowerBound="1"
        upperBound="-1" eType="#//EcoreID" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
