<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://deltaecore.org/feature/configuration/1.0"
    nsPrefix="configuration">
  <eClassifiers xsi:type="ecore:EClass" name="DEConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationArtifacts"
        lowerBound="1" upperBound="-1" eType="#//DEConfigurationArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModel" eType="ecore:EClass ../../org.deltaecore.feature/model/Feature.ecore#//DEFeatureModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEConfigurationArtifact" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DEFeatureSelection" eSuperTypes="#//DEConfigurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass ../../org.deltaecore.feature/model/Feature.ecore#//DEFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEVersionSelection" eSuperTypes="#//DEConfigurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../org.deltaecore.feature/model/Feature.ecore#//DEFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="ecore:EClass ../../org.deltaecore.feature/model/Feature.ecore#//DEVersion"/>
  </eClassifiers>
</ecore:EPackage>
