<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="feature" nsURI="http://www.tu-bs.de/snowflake/feature/1.0" nsPrefix="feature">
  <eClassifiers xsi:type="ecore:EClass" name="SFeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFeature" lowerBound="1"
        eType="#//SFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFeature" eSuperTypes="#//SCardinalityBasedElement #//SGroupArtifact">
    <eOperations name="isOptional" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (getMinCardinality() == 0 &amp;&amp; getMaxCardinality() == 1);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isMandatory" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (getMinCardinality() == 1 &amp;&amp; getMaxCardinality() == 1);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getParentGroup" lowerBound="1" eType="#//SGroup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (SGroup) eContainer();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getParentFeature" lowerBound="1" eType="#//SFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (getParentGroup() != null) {&#xD;&#xA;&#x9;return getParentGroup().getParentFeature();&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//SVersion" containment="true" eOpposite="#//SVersion/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//SGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SGroup" eSuperTypes="#//SCardinalityBasedElement">
    <eOperations name="isAnd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="int optionalFeatures = 0;&#xD;&#xA;int mandatoryFeatures = 0;&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;for (SGroupArtifact artifact : getArtifacts()) {&#xD;&#xA;&#x9;if (artifact instanceof SFeature) {&#xD;&#xA;&#x9;&#x9;SFeature feature = (SFeature) artifact;&#xD;&#xA;&#x9;&#x9;if (feature.isOptional()) {&#xD;&#xA;&#x9;&#x9;&#x9;optionalFeatures++;&#xD;&#xA;&#x9;&#x9;} else if (feature.isMandatory()) {&#xD;&#xA;&#x9;&#x9;&#x9;mandatoryFeatures++;&#xD;&#xA;&#x9;&#x9;}&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;return (getMinCardinality() &lt;= mandatoryFeatures &amp;&amp; getMaxCardinality() >= (mandatoryFeatures + optionalFeatures));"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isOr" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (getMinCardinality() == 1 &amp;&amp; getMaxCardinality() == getArtifacts().size());"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isAlternative" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (getMinCardinality() == 1 &amp;&amp; getMaxCardinality() == 1);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getParentFeature" lowerBound="1" eType="#//SFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (SFeature) eContainer();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" lowerBound="1"
        upperBound="-1" eType="#//SGroupArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SCardinalityBasedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UNLIMITED_MAX_CARDINALITY"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//SFeature" eOpposite="#//SFeature/versions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supersedingVersions" upperBound="-1"
        eType="#//SVersion" eOpposite="#//SVersion/supersededVersion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supersededVersion" eType="#//SVersion"
        eOpposite="#//SVersion/supersedingVersions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SConfigurationArtifact" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SFeatureSelection" eSuperTypes="#//SConfigurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//SFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SVersionSelection" eSuperTypes="#//SConfigurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//SVersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SGroupArtifact" abstract="true" interface="true"/>
</ecore:EPackage>
